### ISSUE TITLE
What happened to ClearInputAndSendKeys?

### ISSUE THREAD

**Issue by tobyweston** [alltonp/flakeless#4]
Trawling through the commits, did `ClearInputAndSendKeys` get replaced with vanilla `SendKeys`?

So, 

```scala
ClearInputAndSendKeys(driver, path, List(value, Keys.END))
```
becomes

```scala
SendKeys(driver, path, clear = true, List(value, Keys.END))
```
***?***

...and any uses of `SendKeys` now needs a value?

So,
```scala
SendKeys(driver, dealLogIdPath, Keys.TAB)
```
becomes

```scala
SendKeys(driver, dealLogIdPath, clear = false, Keys.TAB)
```
***?***

**Comment by alltonp** [comment]
Yes, that's correct. It was a refactor to remove duplication of having both SendKeys and ClearInputAndSendKeys
